# Generated by Django 3.2.19 on 2023-06-14 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20230526_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default='s@gmail.com', max_length=255),
        ),
    ]
