# Generated by Django 3.2.19 on 2023-05-11 11:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("buddies", "0002_auto_20230511_1135"),
    ]

    operations = [
        migrations.RenameField(
            model_name="buddy",
            old_name="owner",
            new_name="user",
        ),
    ]
