# Generated by Django 3.2.19 on 2023-05-11 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("buddies", "0003_rename_owner_buddy_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buddy",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile_owner",
                to="buddies.userprofile",
            ),
        ),
    ]
