# Generated by Django 3.2.19 on 2023-05-11 11:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("buddies", "0004_alter_buddy_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="buddy",
            old_name="user",
            new_name="user_profile",
        ),
    ]
