# Generated by Django 3.2.19 on 2023-05-12 12:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("buddies", "0005_rename_user_buddy_user_profile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="email",
        ),
    ]
