# Generated by Django 3.2.19 on 2023-05-16 11:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("buddies", "0011_buddy_picture_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buddy",
            name="picture_description",
            field=models.CharField(max_length=200),
        ),
    ]
