# Generated by Django 3.2.19 on 2023-05-18 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buddies', '0012_alter_buddy_picture_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buddy',
            old_name='data_of_birth',
            new_name='date_of_birth',
        ),
    ]
