# Generated by Django 3.2.19 on 2023-05-18 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buddies', '0014_buddy_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buddy',
            name='user',
        ),
    ]
