# Generated by Django 3.2.19 on 2023-05-26 11:18

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20230526_1118'),
        ('buddies', '0018_auto_20230526_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buddy',
            name='about_me',
            field=models.TextField(default='Describe yourself'),
        ),
        migrations.AlterField(
            model_name='buddy',
            name='picture_description',
            field=models.CharField(default='A picture of me', max_length=200),
        ),
        migrations.AlterField(
            model_name='buddy',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='buddy',
            name='user_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='buddy', to='profiles.userprofile'),
            preserve_default=False,
        ),
    ]
