# Generated by Django 3.2.19 on 2023-06-09 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buddies', '0019_auto_20230526_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buddy',
            name='availability',
            field=models.CharField(choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon'), ('Both Morning and Afternoon', 'Both Morning and Afternoon')], default='Both', max_length=50),
        ),
        migrations.AlterField(
            model_name='buddy',
            name='game_type',
            field=models.CharField(choices=[('Singles', 'Singles'), ('Doubles', 'Doubles'), ('Both Singles and Doubles', 'Both Singles and Doubles')], default='Singles', max_length=50),
        ),
        migrations.AlterField(
            model_name='buddy',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='M', max_length=6),
        ),
        migrations.AlterField(
            model_name='buddy',
            name='practice_type',
            field=models.CharField(choices=[('Hitting Practice', 'Hitting Practice'), ('Match Practice', 'Match Practice'), ('Both Match and Hitting Practice', 'Both Match and Hitting Practice')], default='Both', max_length=50),
        ),
    ]
