# Generated by Django 3.2.19 on 2023-06-14 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buddies', '0020_auto_20230609_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='buddy',
            name='email',
            field=models.EmailField(default='l@gmail.com', max_length=150),
        ),
    ]
