# Generated by Django 3.2.19 on 2023-06-14 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buddies', '0021_buddy_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buddy',
            name='email',
            field=models.EmailField(max_length=150),
        ),
    ]
