# Generated by Django 3.2.19 on 2023-06-01 12:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_auto_20230526_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='court',
            field=models.ForeignKey(default='one', on_delete=django.db.models.deletion.CASCADE, to='bookings.court'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
