# Generated by Django 3.2.19 on 2023-06-09 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0011_auto_20230601_1227'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(fields=('date', 'time', 'court'), name='unique_booking'),
        ),
    ]
