# Generated by Django 3.2.19 on 2023-06-12 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0012_booking_unique_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='court',
            old_name='court_name',
            new_name='name',
        ),
    ]
